"use strict";

/* THE FLEET SERVICING PANEL on the Mine tab. Pulled out of mine-market.js, which is at its size ceiling. */

function fleetServicingVisual(){
  const covid=covidPartsMarket(),multiplier=covid?2.25:1,technicians=fieldTechnicianCount(),owned=HARDWARE.filter(h=>(state.hardware[h.id]||0)>0);
  const needsHelp=owned.some(h=>hardwareFaultCount(h)>0||maintenanceCondition(h)<65);
  const hireNudge=!needsHelp||technicians>0?"":staffHiringAvailable()?`<div class="maintenance-nudge"><span>No field technicians on payroll - you service the fleet yourself. Labour is free, but only one job at a time and a fumbled repair can damage the machine.</span><button class="action small primary" data-action="hire-staff" data-id="fieldtech">Hire field technician · ${fmtUsd(1200)}/month</button></div>`:`<div class="maintenance-nudge"><span>You are maintaining the fleet yourself: free labour, one job at a time, and a real chance of damaging a machine. Hire field technicians once you reach a Light industrial unit (tier 3).</span></div>`;
  const rows=owned.map(h=>{
    const n=state.hardware[h.id],health=maintenanceCondition(h),breakdown=hardwareFaultBreakdown(h),faults=Object.values(breakdown).reduce((sum,c)=>sum+c,0),faultedFraction=n?faults/n:0,job=activeServiceJob(h.id),refurbCount=health<65?n:Math.max(faults,Math.ceil(n*.15)),refurbRequirements=serviceRequirements(h,refurbCount),refurbPlan=servicePlan(h,refurbCount),refurbNeeded=health<95||faults>0,daysLeft=job?Math.max(0,Math.ceil((job.due-state.time)/DAY)):0;
    const stageIdx=job&&Number.isFinite(job.stage)?Math.min(job.stage,REPAIR_STAGES.length-1):null,stageName=stageIdx!==null?REPAIR_STAGES[stageIdx].name:null,awaitingInput=!!(job&&!job.auto&&job.contracted&&REPAIR_STAGES[job.stage]?.id==="work"&&!job.workDone);
    /* A pending settlement stops the clock, so a repair started under one cannot progress. It
       used to keep advertising "1d left" against a day that could never arrive. */
    const clockHeld=!!state.pendingSettlement,progress=awaitingInput?"awaiting you":clockHeld?"paused · settle the bill first":`${daysLeft}d left`;
    const status=job?(job.part?`Replacing ${sparePart(job.part)?.name||job.part}${stageName?` · ${stageName}`:""} · ${progress}`:`Full refurbishment in progress${stageName?` · ${stageName}`:""} · ${progress}`):hardwareOfflineReason(h)||(faults?`${faults} unit${faults===1?"":"s"} faulted`:"Operating");
    const stageTrack=stageIdx!==null?`<div class="repair-stage-track">${REPAIR_STAGES.map((s,i)=>`<i class="${i<stageIdx?"done":i===stageIdx?"active":""}" title="${s.name}"></i>`).join("")}</div>`:"";
    const workPuzzle=job&&!job.auto&&job.contracted&&REPAIR_STAGES[job.stage]?.id==="work"&&!job.workDone?repairWorkPuzzle(h,job):"";
    const partRows=Object.entries(breakdown).filter(([,count])=>count>0).map(([part,count])=>{
      const partDef=sparePart(part),qty=Math.max(1,Math.ceil(count/7)),have=hasServiceParts({[part]:qty}),cost=sparePartCost(partDef)*qty;
      const stock=state.maintenance.inventory[part]||0,missing=Math.max(1,qty-stock);
      const mine=(state.maintenance.orders||[]).filter(o=>(o.type||"fan")===part);
      const inboundQty=mine.reduce((sum,o)=>sum+(Number(o.qty)||0),0),inboundDue=mine.map(o=>o.due).sort((a,b)=>a-b)[0];
      const shortNote=have?"":`<em class="part-short">${stock} in stock of ${qty} needed${inboundQty?` · ${inboundQty} arriving ${dateFmt(inboundDue)}`:" · none on order"}</em>`;
      const orderCost=sparePartCost(partDef)*missing;
      return `<div class="part-fault-row"><span>${PART_FAULT_LABELS[part]||partDef?.name||part} <b>×${count}</b></span>${shortNote}${have?`<button class="action small primary" data-action="service-part" data-id="${h.id}" data-part="${part}" ${serviceBlockReason(h,part)?"disabled":""} title="${escapeHtml(serviceBlockReason(h,part))}">Replace ${qty} ${partDef?.name||part}${qty===1?"":"s"}</button>`:`<button class="action small ${inboundQty>=missing?"":"primary"}" data-action="order-parts" data-id="${part}" data-value="${missing}" ${state.cash<orderCost?"disabled":""} title="${state.cash<orderCost?"Not enough cash":inboundQty>=missing?`${inboundQty} are already on the way - this orders ${missing} more`:`Order the ${missing} missing`}">Order ${missing} ${partDef?.name||part}${missing===1?"":"s"} · ${fmtUsd(orderCost)}</button>`}</div>`;
    }).join("")||`<div class="part-fault-row empty">No part-specific faults reported</div>`;
    return `<div class="maintenance-row" data-service-row="${h.id}"><div class="balance-name">${h.name}<small>${n} units · ${status}</small>${stageTrack}${workPuzzle}<div class="bar" style="--w:${health}%;--bar:${health<65||faultedFraction>.05?"var(--red)":health<80||faultedFraction>.01?"var(--orange)":"var(--green)"}"><i></i></div></div><div class="maintenance-row-actions">${partRows}<button class="action small ${health<65?"primary":""}" data-action="service-hw" data-id="${h.id}" ${serviceBlockReason(h)?"disabled":""} title="${escapeHtml(serviceBlockReason(h))}">Refurbish ${refurbCount}${Number.isFinite(refurbPlan.days)?` · ${refurbPlan.days}d`:" · no crew free"}</button></div></div>`;
  }).join("")||`<div class="empty-story">No serviceable mining hardware is installed.</div>`;
  const spares=SPARE_PARTS.map(part=>{const fit=partFitSummary(part.id),onOrder=state.maintenance.orders.filter(order=>(order.type||"fan")===part.id).reduce((sum,order)=>sum+order.qty,0),unit=sparePartCost(part),list=part.cost*(covid?2.25:1);return `<article class="venue">${sparePartSvg(part.id)}<div class="risk ${(state.maintenance.inventory[part.id]||0)>0?"low":"medium"}">SPARE PART</div><h3>${part.name}</h3><div class="part-stock"><b>${fmtNum(state.maintenance.inventory[part.id]||0)}</b><span>in stock</span></div><p>${part.desc}</p><div class="part-fit ${fit.fits?"":"unused"}">${fit.text}</div><div class="trade-sub">${onOrder?`${onOrder} on order, due ${dateFmt(state.maintenance.orders.filter(o=>(o.type||"fan")===part.id).map(o=>o.due).sort((a,b)=>a-b)[0])}`:"none on order"} · ${fmtUsd(unit)} each${unit<list-1e-9?` (was ${fmtUsd(list)})`:""} · ${partsLeadDays()}-day lead</div><div class="actions"><button class="action small primary" data-action="order-parts" data-id="${part.id}" data-value="1" ${state.cash<unit?"disabled":""} title="${state.cash<unit?"Not enough cash":""}">Order 1</button><button class="action small" data-action="order-parts" data-id="${part.id}" data-value="5" ${state.cash<unit*5?"disabled":""} title="${state.cash<unit*5?"Not enough cash":""}">Order 5</button><button class="action small" data-action="order-parts" data-id="${part.id}" data-value="50" ${state.cash<unit*50?"disabled":""} title="${state.cash<unit*50?"Not enough cash":""}">Order 50</button><button class="action small" data-action="order-parts-bulk" data-id="${part.id}" data-value="500" ${state.cash<unit*500?"disabled":""} title="${state.cash<unit*500?`500 cost ${fmtUsd(unit*500)}; you have ${fmtUsd(state.cash)}`:`${fmtUsd(unit*500)} · confirmed before it is placed`}">Order 500</button></div></article>`}).join("");
  const autoRepairToggle=`<div class="auto-repair-toggle ${state.autoRepair?"on":""}"><div><b>Auto-repair</b><span>${technicians>0?"Your technician crew works continuously on any faulted unit while parts are in stock.":"Hire a field technician to enable continuous automatic repairs."}</span></div><button class="action small ${state.autoRepair?"danger":"primary"}" data-action="toggle-auto-repair" ${technicians<1?"disabled":""}>${state.autoRepair?"Disable":"Enable"} auto-repair</button></div>`;
  return `<section class="card span-12 fleet-servicing"><div class="card-head"><h2>Fleet servicing</h2><div class="meta">${covid?"COVID SUPPLY SHOCK":"NORMAL PARTS MARKET"} · ${partsLeadDays()}-DAY LEAD TIMES</div></div><div class="card-pad">${hireNudge}${firmwareStatusHtml()}${partsStatusStrip()}${selfServiceRelevant()?selfServiceBench(owned):""}${autoRepairToggle}<div class="venue-grid">${spares}</div><div class="balance-list" style="margin-top:10px">${rows}</div><p class="modal-note">Random faults are now attributed to a specific part - hashboard, power PCB, fan or hydro coolant hardware - and each can be swapped independently once parts are in stock. Condition still falls with wear and use; below 65% the whole type needs a full refurbishment. <button class="action small" data-action="tab" data-value="method" data-anchor="method-maintenance">How this works →</button></p></div></section>`;
}
