"use strict";

function workshopArt(product){return product?.art||(product?.build?"qr-signer":"hardware-wallet")}
function workshopImage(id,alt=""){return `<img class="custody-equipment-art" src="assets/custody/${id}.svg" alt="${escapeHtml(alt)}">`}
function workshopButton(action,id,label,value="",disabled=false){return `<button class="action small" data-action="${action}" data-id="${id}" data-value="${value}"${disabled?" disabled":""}>${label}</button>`}
function workshopChoice(){
  const c=state.custody,w=c.workshop||{group:"offline"},group=["offline","qr","hardware","nodes"].includes(w.group)?w.group:"offline";
  const devices=(c.devices||[]).filter(d=>!d.destroyed&&workshopGroup(custodyProduct(d.product))===group);
  return {group,devices,device:devices.find(d=>d.uid===w.uid)||devices.find(d=>workshopProgress(d)<100)||devices[0]};
}
function workshopOptions(){
  const current=workshopChoice(),c=state.custody;
  return `<div class="custody-purpose" aria-label="Choose custody setup">${[["offline","Sign offline","A computer with one job"],["qr","Build a QR signer","A camera carries the payment"],["hardware","Hardware wallets","A signer and its client"],["nodes","Nodes","Bitcoin + Lightning upgrades"]].map(([group,title,job])=>{
    const devices=(c.devices||[]).filter(d=>!d.destroyed&&workshopGroup(custodyProduct(d.product))===group),orders=(c.orders||[]).filter(o=>workshopGroup(custodyProduct(o.id))===group&&custodyProduct(o.id)?.kind==="signer");
    const ready=group==="nodes"?(state.node>0&&primaryNodeOnline()?1:0):devices.filter(d=>workshopProgress(d)===100).length;
    const qrParts=group==="qr"?Object.keys(CUSTODY_BUILDS.seedsigner.required):[];
    const partOrders=group==="qr"?(c.orders||[]).filter(o=>qrParts.includes(o.id)||o.id==="sskit"):[];
    const partsReady=qrParts.filter(id=>(c.parts[id]||0)>0).length;
    const pending=orders.reduce((n,o)=>n+o.qty,0)+(group==="qr"?(c.builds||[]).length+partOrders.length:0),owned=group==="nodes"?Number(state.node>0):devices.length;
    const active=group===current.group?current.device:devices.find(d=>workshopProgress(d)<100)||devices[0];
    const percent=group==="nodes"?(state.node>0?nodeSyncProgress(state.nodeSync.primaryLag,state.nodeSync.primaryPeak):0):active?workshopProgress(active):group==="qr"?Math.round(partsReady/4*16):0;
    return `<button class="action custody-purpose-option" data-action="workshop-select" data-id="${group}" aria-pressed="${current.group===group}" data-started="${!!(owned||pending||partsReady)}"><b>${title}</b><small>${job}</small><span>${owned} owned · ${ready} ready${pending?` · ${pending} arriving`:""}</span><span>${percent}% setup</span><div class="bar" role="progressbar" aria-label="${title} setup" aria-valuenow="${percent}" aria-valuemin="0" aria-valuemax="100" style="--w:${percent}%;--bar:var(--orange)"><i></i></div></button>`;
  }).join("")}</div>`;
}
function workshopStory(device){
  if(!device)return ["A place for the secret","grok69420 offers the computer he uses for games, invoices and a suspicious number of browser extensions. You choose a separate machine with one job.","Buying a device creates neither a key nor a recovery plan. Choose equipment for the signing role."];
  const p=custodyProduct(device.product),k=device.keyId?custodyKey(device.keyId):null,s=workshopSteps(device).findIndex(done=>!done);
  if(k?.exposed)return ["The envelope is still there. The secret is no longer yours alone.","Nothing about a neatly folded recovery copy tells you whether somebody has already photographed it.","This key is known to somebody else. Rotate it using the individual device records below. Moving the backup or wiping one device does not revoke other copies; moving the funds to a replacement spending rule does."];
  if(s===1)return ["The parcel is not the proof","grok69420 points at the tamper-proof sticker. claude1337 asks who sent the parcel and what checks you have actually made.","Inspect the source and delivery. A clean-looking case cannot prove that electronics or software are trustworthy."];
  if(s===2)return ["The box still needs an interpreter",p?.computer?"The new PC could do a hundred things. You install software for one: inspect a payment and sign it offline.":"grok69420 expects the small device to do everything. The client still prepares payments, gets chain data and carries messages to the signer.","Client software adds another dependency. Check its source, compatibility and updates. Chain data comes through the online payment-preparation computer; this choice does not connect the offline signer to the network. Review recipient and amount on the signing device before approving."];
  if(s===3)return ["A secret becomes authority","No passport. No security question. No mother's maiden name. You are about to create a secret that the spending rule will recognise.","A PIN can protect a device. It cannot make a helpdesk replace a lost signing secret. Generate here, then prepare recovery."];
  if(s===4)return ["Plan for the day the box goes quiet","grok69420 recommends restarting it. You would like a plan that survives the second attempt.","A recovery copy can restore the same signing authority. It also creates another place where the secret can be read."];
  if(k?.backup&&(!k.backup.place||k.backup.place==="transit"))return ["The recovery route is not settled yet",k.backup.place==="transit"?"The copy is travelling. grok69420 has announced that it is safe at both ends. It has not arrived at either.":"grok69420 writes “somewhere safe” on the storage plan. claude1337 asks for a location.","The location map shows unrecorded or in-transit material separately. Wait for arrival or record a real storage destination before treating separation as established."];
  if(k?.backup?.place==="trusted")return ["grok69420 discovers what the words can do","Your friend thought the envelope was very dull. Then they learn what Bitcoin is. Most friendships survive this discovery; the game leaves a very small chance yours does not.","Readable backups at a friend's house have a 0.06% monthly betrayal baseline, equal to flooding there. The envelope can remain intact while the secret is copied. A bank box has no friend-access roll. Rotate an exposed key; retrieving its copy does not revoke another copy."];
  if(k&&!workshopSeparate(k))return ["Two containers, one address","grok69420 files the copy in the next drawer and calls it double security. claude1337 draws one circle around the building.","One incident can still reach device and recovery material. Choose a different site and check who can read the copy there."];
  return ["Make the plan outlive the afternoon","grok69420 starts printing an IMPOSSIBLE TO LOSE label. You ask him to leave space for the date of a recovery rehearsal.","Setup recorded is not recovery tested. Extra copies of one secret remain one key, and several backups at one second address still share an incident."];
}
function workshopDevicePanel(device){
  const c=state.custody,{group,devices}=workshopChoice(),products=CUSTODY_PRODUCTS.filter(p=>p.kind==="signer"&&workshopGroup(p)===group&&custodyProductAvailable(p)),p=device?custodyProduct(device.product):null,k=device?.keyId?custodyKey(device.keyId):null;
  const pick=devices.map(d=>workshopButton("workshop-select",group,`${custodyProduct(d.product)?.name||"Signer"} ${d.uid} · ${workshopProgress(d)}%`,d.uid)).join("");
  const next=products.length?null:CUSTODY_PRODUCTS.filter(p=>p.kind==="signer"&&workshopGroup(p)===group).sort((a,b)=>a.date.localeCompare(b.date))[0];
  let actions="";
  if(device){
    const s=workshopSteps(device).findIndex(done=>!done);
    if(s===1)actions=workshopButton("workshop-inspect",device.uid,"Inspect delivery and source");
    else if(s===2)actions=`<div class="workshop-client"><label>Signing client<select data-workshop-client="client" data-device="${device.uid}">${[["vendor",p?.computer?"Checked offline wallet client":"Manufacturer client"],["independent","Compatible independent client"]].map(([v,n])=>`<option value="${v}"${(device.client||"vendor")===v?" selected":""}>${n}</option>`).join("")}</select></label><label>Payment coordinator?s chain data<select data-workshop-client="chainSource" data-device="${device.uid}">${[["provider","Client provider"],["own","Your available node"]].map(([v,n])=>`<option value="${v}"${(device.chainSource||"provider")===v?" selected":""}${v==="own"&&!nodeOnline()?" disabled":""}>${n}</option>`).join("")}</select></label></div>${workshopButton("workshop-prepare",device.uid,"Record software and payment-review checks")}`;
    else if(s===3)actions=workshopButton("custody-genkey",device.uid,"Create a signing key");
    else if(s===4)actions=workshopButton("custody-backup",k.id,"Record paper recovery · free","paperbackup");
    else if(s===5)actions=workshopButton("custody-assign",k.id,"Assign key to reserve wallet");
  }
  let [title,scene,why]=workshopStory(device);
  if(next&&!device){title="This equipment has not arrived in the story yet";scene=`${next.name} becomes available from ${dateFmt(at(next.date),true)}. grok69420 has volunteered to invent it sooner. claude1337 suggests using a computer kept offline for now.`;why="The catalogue follows the campaign date. The key, backup and spending-rule concepts apply before dedicated signing hardware appears.";}
  return `<div class="workshop-inventory"><h3>${devices.length} owned · ${devices.filter(d=>workshopProgress(d)===100).length} ready for the wallet</h3><div class="actions">${pick}</div></div><div class="workshop-build"><div><h3>${p?.name||"Choose equipment"}</h3>${device?`<ol class="workshop-checks">${["Equipment delivered","Source inspected","Signing client prepared","Key created","Recovery recorded","Assigned to wallet"].map((label,i)=>`<li>${workshopSteps(device)[i]?"✓":"×"} ${label}</li>`).join("")}</ol>`:""}<div class="actions">${actions}</div></div><section class="workshop-story"><span class="meta">CLAUDE1337 / GROK69420</span><h3>${title}</h3><p>${scene}</p><b>Why this matters</b><p>${why}</p></section></div><details class="workshop-catalogue"${!device?" open":""}><summary>${device?"Buy another signer":"Available equipment"}</summary><div class="venue-grid">${products.filter(p=>!p.build).map(p=>`<article class="venue">${workshopImage(workshopArt(p))}<h3>${p.name}</h3><p>${p.desc}</p>${workshopButton("custody-buy",p.id,`Order · ${fmtUsd(custodyUnitCost(p))} · ${custodyLeadDays(p)}d`,"",custodyCash(p)<custodyUnitCost(p))}</article>`).join("")}</div>${group==="qr"?`<p class="modal-note">Order the component kit or individual parts below, then assemble the SeedSigner. Its boot card starts the software; it is not recovery material.</p>`:""}</details>`;
}
function workshopNodesPanel(){
  const available=lightningAvailable();
  return `<div class="workshop-build"><section><h3>Bitcoin node</h3><p>A node checks the chain. Its data can be downloaded again; a signing secret needs its own recovery route.</p><p>${state.node?`${nodeDeploymentName()} · ${nodeSyncProgress(state.nodeSync.primaryLag,state.nodeSync.primaryPeak)}% primary sync`:"The mining laptop currently shares verification. A dedicated node gives it a separate operating role."}</p><div class="actions">${state.node<1?workshopButton("buy-node","","Deploy dedicated node · $260","1"):state.node<2&&state.time>=at("2016-01-01")?workshopButton("buy-node","","Upgrade hardened node · $1,200","2"):""}</div><p class="modal-note">Storage, profile and remote-backup controls remain in Full-node operations below.</p></section><section class="workshop-story"><span class="meta">UPGRADE THIS NODE</span><h3>Lightning</h3><p>grok69420 asks when the node starts earning interest. It does not. Routing uses online spending keys and payment-channel liquidity, with its own recovery needs.</p><p>${available?"Bitcoin verification is ready for the game's Lightning upgrade.":(state.time<LIGHTNING?'Lightning routing becomes available in 2018.':state.node<1?'Deploy a dedicated Bitcoin node first.':state.nodeMode==='pruned'?'Use archival or relay mode for Lightning.':'Bring the primary node to the chain tip first.')}</p><p>Wallet recovery and channel recovery are different jobs. A reserve seed alone does not reconstruct a Lightning channel. Keep working funds separate from reserves.</p><div class="actions">${workshopButton("tab","","Open routing liquidity in Market","market")}</div></section></div>`;
}
function workshopLocations(){
  const rows=workshopConcentration(),clustered=rows.filter(s=>s.id!=="unknown"&&s.keys+s.copies>1).length;
  const {device}=workshopChoice(),key=device?.keyId?custodyKey(device.keyId):null;
  const controls=device?placeItemRow("device",device.uid,"Place this signer",`Currently ${custodyPlaceName(device.place)}`,device.place)+(key?.backup&&!key.backup.destroyed?placeItemRow("backup",key.id,"Place its recovery copy",`Currently ${custodyPlaceName(key.backup.place)}. Moving takes simulated days.`,key.backup.place):""):"";
  return `<details class="workshop-locations"><summary>Keys and backups by site · ${clustered} shared location${clustered===1?"":"s"}</summary><p>Two drawers at one address still share a fire or burglary. Several backups at one second address share another incident. Storage at a friend's home also introduces access risk.</p><table><thead><tr><th>Site</th><th>Distinct keys</th><th>Recovery copies</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${r.id==="unknown"?"Unrecorded or in transit":custodyPlaceName(r.id)}</td><td>${r.keys}</td><td>${r.copies}</td></tr>`).join("")||'<tr><td colspan="3">Create a reserve key to start this map.</td></tr>'}</tbody></table>${controls}<p class="modal-note">A bank box avoids the friend-access roll; it still has its own access, physical and seizure risks. Readable seed backups at a friend's home have a 0.06% monthly betrayal baseline, matching flooding there. A locked hardware wallet alone does not trigger that roll. Counts describe the simulation, not verified real storage.</p></details>`;
}
function custodyWorkshopCard(){
  const {group,device}=workshopChoice(),h=workshopHealth(),art=group==="nodes"?"bitcoin-node":device?workshopArt(custodyProduct(device.product)):group==="qr"?"qr-signer":group==="hardware"?"hardware-wallet":"basic-pc";
  return `<section class="card span-12 custody-workshop"><div class="card-head"><h2>Your custody workshop</h2><div class="meta">BUILD / CHECK / RECOVER</div></div><div class="card-pad"><div class="metric-row"><div class="metric"><div class="label">Reserve setup health</div><strong>${h.score} / 100</strong><small>Lowest created-key checklist score</small></div><div class="metric"><div class="label">Recovery material</div><strong>${h.backups} / ${h.keys}</strong><small>${h.separate} apart from their working devices</small></div><div class="metric"><div class="label">Spending rule</div><strong>${custodySetup().policy.threshold} of ${custodySetup().policy.keys}</strong><small>Distinct secrets authorise spending</small></div></div><details><summary>What this score means</summary><p>Inspection 10, software preparation 15, key creation 10, recovery recorded 20, distinct storage sites 20, wallet assignment 10. Recovery rehearsal is not implemented, so the maximum is 85. This is a checklist, not the chance your coins are safe. A copied seed can remain physically intact; key exposure is shown separately below. Buying hardware or a node earns no safety points.</p></details>${workshopOptions()}${workshopLocations()}<div class="workshop-floor" aria-label="Custody equipment floor"><div class="workshop-plane" aria-hidden="true"></div><button class="workshop-station" data-action="workshop-select" data-id="${group}" aria-label="Selected build">${workshopImage(art)}<span>${group==="nodes"?"Bitcoin node":custodyProduct(device?.product)?.name||"Signing bench"}</span></button><button class="workshop-station recovery-station" data-action="workshop-locations">${workshopImage("steel-backup")}<span>Recovery storage</span></button><button class="workshop-station node-station" data-action="workshop-select" data-id="nodes">${workshopImage("lightning-node")}<span>Lightning upgrade</span></button></div>${group==="nodes"?workshopNodesPanel():workshopDevicePanel(device)}</div></section>`;
}
