"use strict";

function milestonesLedgerSection(){
  const hit=MILESTONES.filter(m=>state.milestones.includes(m.id)),pending=MILESTONES.filter(m=>!state.milestones.includes(m.id));
  const hitRows=hit.map(m=>{const entry=state.milestoneLog.find(x=>x.id===m.id);return `<div class="milestone-row hit"><div><b>${m.label}</b><span>${entry?dateFmt(entry.time,true):""}</span></div><p>${m.blurb}</p></div>`}).join("");
  const pendingRows=pending.map(m=>`<div class="milestone-row pending"><div><b>${m.label}</b><span>Not yet reached</span></div><p>${m.blurb}</p></div>`).join("");
  return `<section class="card span-12"><div class="card-head"><h2>Operator milestones</h2><div class="meta">${hit.length} / ${MILESTONES.length} REACHED</div></div><div class="card-pad milestone-grid">${hitRows}${pendingRows}</div></section>`;
}
function activityLedger(){
  const filters=["all",...ACTIVITY_CATEGORIES],filtered=activityFilter==="all"?state.activity:state.activity.filter(entry=>entry.category===activityFilter),visible=filtered.slice(0,activityLimit),counts=Object.fromEntries(ACTIVITY_CATEGORIES.map(kind=>[kind,state.activity.filter(entry=>entry.category===kind).length])),latest=state.activity[0];
  const rows=visible.map(entry=>{const amount=escapeHtml(entry.amount),amountClass=String(entry.amount).trim().startsWith("+")?"profit-positive":String(entry.amount).trim().startsWith("-")?"profit-negative":"";return `<tr><td><b>${dateFmt(entry.time)}</b><small style="display:block;color:var(--dim)">entry #${fmtNum(entry.id)}</small></td><td><span class="activity-kind ${entry.category}">${escapeHtml(entry.category)}</span></td><td class="action-name">${escapeHtml(entry.text)}${entry.price!==null?`<small>BTC ${fmtUsd(entry.price)}</small>`:""}</td><td class="amount ${amountClass}">${amount||"-"}</td><td class="balance">${entry.cash===null?"-":fmtUsd(entry.cash)}</td><td class="balance">${entry.btc===null?"-":fmtBtc(entry.btc)}</td><td class="balance">${entry.hash===null?"-":fmtHash(entry.hash)}</td></tr>`}).join("");
  return `<div class="grid"><section class="card span-12"><div class="hero"><div><div class="hero-kicker">Permanent activity ledger</div><h1>Every consequential action, payment and event.</h1><p>Trades, fleet changes, bills, rewards, custody moves and operational incidents are stored with the balances immediately after they occur. Filters change the view, never the underlying record.</p></div><div class="hero-stat"><strong>${fmtNum(state.activity.length)}</strong><span>saved ledger entries</span></div></div><div class="metric-row"><div class="metric"><div class="label">Market trades</div><strong>${fmtNum(counts.trade)}</strong><small>BTC, ETF and Strategy orders</small></div><div class="metric"><div class="label">Fleet actions</div><strong>${fmtNum(counts.fleet)}</strong><small>Purchases, sales and maintenance</small></div><div class="metric"><div class="label">Finance actions</div><strong>${fmtNum(counts.finance)}</strong><small>Bills, borrowing and rescues</small></div><div class="metric"><div class="label">Latest entry</div><strong>${latest?dateFmt(latest.time,true):"None"}</strong><small>${latest?escapeHtml(latest.text):"No activity recorded"}</small></div></div></section>${milestonesLedgerSection()}<section class="card span-12"><div class="card-head"><h2>Transaction & action history</h2><div class="meta">${fmtNum(filtered.length)} ${activityFilter==="all"?"TOTAL":"FILTERED"} ENTRIES</div></div><div class="card-pad"><div class="activity-filters">${filters.map(kind=>`<button class="action small ${activityFilter===kind?"primary":""}" data-action="activity-filter" data-value="${kind}">${kind==="all"?`All · ${fmtNum(state.activity.length)}`:`${kind} · ${fmtNum(counts[kind])}`}</button>`).join("")}</div></div><div class="profit-wrap"><table class="activity-table"><thead><tr><th>Date</th><th>Type</th><th>Action</th><th style="text-align:right">Change</th><th style="text-align:right">Cash after</th><th style="text-align:right">Self-held BTC</th><th style="text-align:right">Fleet hash</th></tr></thead><tbody>${rows||`<tr><td colspan="7">No ${escapeHtml(activityFilter)} entries recorded yet.</td></tr>`}</tbody></table></div><div class="card-pad actions">${visible.length<filtered.length?`<button class="action" data-action="activity-more">Show 100 more · ${fmtNum(filtered.length-visible.length)} remaining</button>`:""}<span class="modal-note push">Existing saves can migrate only the eight records retained by the previous version; every new entry is preserved.</span></div></section></div>`;
}
