"use strict";

/* Method is the canonical reference behind every "How this works" link. It opens as
   eight named chapters with a table of contents, so a newcomer meets summaries rather
   than a wall of formulas, and contextual help can deep-link straight to a chapter. */
const methodOpenChapters=new Set(["method-start"]);
function rememberMethodChapter(node){if(!node||!node.id)return;if(node.open)methodOpenChapters.add(node.id);else methodOpenChapters.delete(node.id)}
function recordedMetricSnapshot(){
  return `<section class="strategy-method-guide"><h3>Recorded metric snapshot</h3><p>The historical engine is bundled locally and never changes during a run. It contains a daily observation for every series it can - market price, a 14-day hash rate mean, seven-day fee and transaction means and cumulative block height - plus one exact difficulty value per 2016-block retarget, through ${DATA_META.through||"the historical cutoff"}.</p><table><tr><th>Metric</th><th>Offline points</th><th>How the game uses it</th></tr><tr><td>BTC / USD</td><td>${fmtNum(PRICE.length)}</td><td>Daily market value and fiat revenue</td></tr><tr><td>Difficulty</td><td>${fmtNum(DIFFICULTY.length)}</td><td>One exact step per retarget · primary expected block-yield calculation</td></tr><tr><td>Network hash rate</td><td>${fmtNum(HASH.length)}</td><td>Smoothed context, charts and competitive floor</td></tr><tr><td>Fees / block</td><td>${fmtNum(FEES.length)}</td><td>Seven-day mean added to the subsidy</td></tr><tr><td>Transactions / day</td><td>${fmtNum(TX.length)}</td><td>Seven-day activity context and Lightning scaling</td></tr><tr><td>Fee rate, median and 90th percentile (sat/vB)</td><td>${fmtNum(FEERATE.length+FEERATE_HIGH.length)}</td><td>What a payment or a cold-storage sweep costs on the day, and what jumping the queue costs</td></tr><tr><td>Retarget heights</td><td>${fmtNum(RETARGET_HEIGHT.length)}</td><td>The block each difficulty step began at</td></tr></table><p class="modal-note">Source: <a href="${DATA_META.sourceUrl||"https://community-api.coinmetrics.io/v4/timeseries/asset-metrics"}" target="_blank" rel="noopener">${DATA_META.source||"Coin Metrics Community Network Data"}</a>. Fee rates, retarget heights and the four halving blocks come from <a href="${DATA_META.feeRateSourceUrl||"https://mempool.space/api/v1/mining/blocks/fee-rates/all"}" target="_blank" rel="noopener">mempool.space</a> too, as recorded per day; the fee rates are whole sat/vB, so a day on which most transactions paid less than one reads zero and is priced at the one-satoshi floor. Difficulty comes from <a href="${DATA_META.difficultySourceUrl||"https://mempool.space/api/v1/mining/difficulty-adjustments/all"}" target="_blank" rel="noopener">mempool.space's published difficulty adjustments</a>: one exact value per 2016-block retarget, held until the next one, because that is the only time the protocol changes it. Early competition scaling, hardware economics and operational outcomes remain explicitly modelled for gameplay.</p></section>`;
}
function methodTocHtml(chapters){
  return `<nav class="method-toc" aria-label="Method chapters"><h3>The manual in eight chapters</h3><button class="action small method-glossary-link" data-action="glossary">Look up a term in the glossary</button><ol>${chapters.map((chapter,index)=>`<li><button class="method-toc-link" data-action="method-chapter" data-id="${chapter.id}"><span class="method-toc-number">${index+1}</span><b>${chapter.title}</b><span>${chapter.summary}</span></button></li>`).join("")}</ol></nav>`;
}
function methodDetailIds(body,chapterId){let n=0;return body.replace(/<details class="method-detail">/g,()=>{const id=`${chapterId}-detail-${++n}`;return `<details class="method-detail" id="${id}" ${methodOpenChapters.has(id)?"open":""}>`})}
function methodChapterHtml(chapter,index){
  return `<details class="method-chapter" id="${chapter.id}" ${methodOpenChapters.has(chapter.id)?"open":""}><summary><span class="method-chapter-number">Chapter ${index+1}</span><b>${chapter.title}</b><span class="method-chapter-summary">${chapter.summary}</span></summary><div class="method-chapter-body"><p class="method-chapter-lead">${chapter.lead}</p>${methodDetailIds(chapter.body,chapter.id)}</div></details>`;
}
function method(){
  const chapters=methodChapters();
  return `<article class="card card-pad method"><div class="hero-kicker">Method &amp; game economics</div><h2>Operator manual: what the simulation actually does.</h2><p>Recorded values come from a bundled historical dataset. Derived values are calculated from those recordings. Everything else - hardware pricing, incidents, uptime, fee outcomes and every value after the historical cutoff - is a gameplay model built to expose operating trade-offs, not a forecast or investment advice.</p>${methodTocHtml(chapters)}${chapters.map(methodChapterHtml).join("")}</article>`;
}
function changeLogHtml(){return `<details class="card" style="margin-top:18px"><summary style="cursor:pointer;font:600 12px var(--mono);padding:16px;color:var(--orange2)">Permanent change log · ${CHANGELOG.length} releases</summary><div class="card-pad">${CHANGELOG.map(entry=>`<section style="padding:4px 0 16px"><div class="hero-kicker">${entry.date}</div><h3>${entry.title}</h3><ul>${entry.items.map(item=>`<li>${item}</li>`).join("")}</ul></section>`).join("")}</div></details>`}
function enhanceMethod(){const guide=document.querySelector(".method");if(!guide||guide.dataset.appended)return;guide.dataset.appended="1";guide.insertAdjacentHTML("beforeend",balanceLabHtml()+changeLogHtml());}
