"use strict";

/* Leaving cold storage can be refused for a reason that has nothing to do with the balance:
   a wallet whose assigned keys no longer satisfy its policy cannot produce a signature at all.
   The button checked only the balance, so an unsignable wallet showed an enabled control with
   an empty tooltip that did nothing when clicked - the refusal arrived as a toast after the
   fact. One reason for the button and the action, as everywhere else. */
/* Coins go into cold storage only when there is a wallet that can sign for them: a payout address you cannot spend
   from is a donation. The same rule the pool payout destination applies. */
function coldDepositBlockReason(){
  if((state.wallets.hot||0)<=0)return "No hot-wallet BTC available to move";
  return custodySetup().ready?"":"Cold storage needs a wallet that can sign first. Follow the steps in Set up cold storage on this page: a signer, a key, a backup, then assign the key to the wallet.";
}
function coldMoveBlockReason(){
  if((state.wallets.cold||0)<=0)return "No cold-storage BTC available to move";
  return typeof coldSpendBlockReason==="function"?coldSpendBlockReason():"";
}
function custody(){
  const nodeCopy=state.node===0?`${WALLET_SOFTWARE[state.walletSoftware].name} runs on the Basic laptop and validates the chain independently while that machine is powered and healthy. Shut the mining laptop down and live verification pauses until it returns and catches up.`:state.node===1?"A dedicated full-node appliance stays powered when the mining fleet is manually shut down. Connectivity, storage and account failures can still interrupt it or leave it behind the chain tip.":"Hardened local storage, monitoring and relay infrastructure improve synchronization, propagation and treasury operations.";
  return `<div class="grid"><section class="card span-12"><div class="hero"><div><div class="hero-kicker">Wallets, keys and verification</div><h1>Your keys decide who can spend your bitcoin.</h1><p>A hot or cold wallet holds the private keys you control. An exchange balance is a promise from that company. A full node checks the network's rules, but it does not control your coins.</p></div><div class="hero-stat"><strong>${fmtBtc(controlled())}</strong><span>self-held BTC</span></div></div></section>
    <section class="card span-5"><div class="card-head"><h2>Your node</h2><div class="meta">${nodeDeploymentName().toUpperCase()}</div></div><div class="card-pad"><p style="color:var(--muted);line-height:1.6">${nodeCopy}</p><div class="actions"><button class="action primary" data-action="buy-node" data-value="1" ${state.node>=1||state.cash<260?"disabled":""} title="${state.node>=1?"Already own a dedicated node":state.cash<260?"Not enough cash":""}">Dedicated full node · $260</button><button class="action" data-action="buy-node" data-value="2" ${state.node>=2||state.time<at("2016-01-01")||state.cash<1200?"disabled":""} title="${state.node>=2?"Already own a hardened node":state.time<at("2016-01-01")?"Available from 2016":state.cash<1200?"Not enough cash":""}">Hardened node · $1,200</button></div><div class="metric-row" style="margin:18px -16px -16px"><div class="metric"><div class="label">Verified days</div><strong>${fmtNum(state.nodeDays)}</strong><small>At least one node was at tip</small></div><div class="metric"><div class="label">Live verification</div><strong style="color:${nodeOnline()?"var(--green)":"var(--red)"}">${nodeOnline()?"ONLINE":"OFFLINE"}</strong><small>${nodeVerificationPath()}</small></div></div></div></section>
    <section class="card span-7"><div class="card-head"><h2>Wallet allocation</h2><div class="meta">calculated</div></div><div class="balance-list">${btcBreakdown()}</div></section>
    <section class="card span-12"><div class="card-head"><h2>Self-custody actions</h2></div><div class="card-pad"><p>Your game wallet is ready. Explore how randomness creates a key with an optional demonstration.</p><button class="action small" data-action="wallet-demo">Try the wallet dice demonstration</button>${percentageControl("custody-transfer","Choose how much of the source wallet to move, then pick a direction below.")}<div class="actions" style="margin-top:10px"><button class="action" data-action="transfer" data-from="hot" data-to="cold" data-percent-id="custody-transfer" data-percent-label="Move hot → cold" ${coldDepositBlockReason()?"disabled":""} title="${escapeHtml(coldDepositBlockReason())}">Move hot → cold ${formatPercent(tradePercentage("custody-transfer"))}%</button><button class="action" data-action="transfer" data-from="cold" data-to="hot" data-percent-id="custody-transfer" data-percent-label="Move cold → hot" ${coldMoveBlockReason()?"disabled":""} title="${escapeHtml(coldMoveBlockReason())}">Move cold → hot ${formatPercent(tradePercentage("custody-transfer"))}%</button><span class="push label">${custodySetup().ready?"Cold storage ready":"Cold storage needs a signer: see Set up cold storage"}</span></div></div></section></div>`
}
function facilities(){
  const fs=fleet(),mc=monthlyCost(),move=state.relocationJob,destination=move?REGIONS.find(r=>r.id===move.id):null,days=move?Math.max(0,Math.ceil((move.due-state.time)/DAY)):0,upgradeJob=state.facilityUpgradeJob,upgradeDestination=upgradeJob?FACILITIES.find(x=>x.id===upgradeJob.id):null,upgradeDays=upgradeJob?Math.max(0,Math.ceil((upgradeJob.due-state.time)/DAY)):0,busy=move||upgradeJob;return `<div class="grid"><section class="card span-12"><div class="hero"><div><div class="hero-kicker">Site capacity and location</div><h1>${region().name} · ${facility().name}</h1><p>Your site must provide enough electrical capacity and floor space for every machine. The region sets electricity price and reliability; relocating costs cash and keeps the fleet offline during the move.</p></div><div class="hero-stat"><strong>${fmtUsd(mc.total)}/month</strong><span>${fmtUsd(mc.rate)}/kWh · ${(region().rely*100).toFixed(1)}% base uptime</span></div></div><div class="metric-row"><div class="metric"><div class="label">Power used</div><strong>${fs.kw.toFixed(2)} / ${fs.cap.toFixed(1)} kW</strong></div><div class="metric"><div class="label">Floor space used</div><strong>${fs.space} / ${facility().space}</strong></div><div class="metric"><div class="label">Bill so far</div><strong>${fmtUsd(state.bill)}</strong></div><div class="metric"><div class="label">Site status</div><strong style="color:${operating()?"var(--green)":"var(--red)"}">${move?"IN TRANSIT":upgradeJob?(upgradeJob.down?"DOWNSIZING":"UPGRADING"):operating()?"ONLINE":"OFFLINE"}</strong></div></div></section>${move?`<section class="card span-12"><div class="card-pad"><div class="lifecycle-flow"><div class="retired"><b>${fs.count}</b><span>Fleet packed</span></div><i>→</i><div class="active"><b>${days}</b><span>Days to ${destination?.name||move.id}</span></div><i>→</i><div><b>${destination?.name||move.id}</b><span>Site commissioning</span></div></div><p class="modal-note">Relocation is underway. Mining stays offline until arrival; rent, staff and other fixed overhead still accrue.</p></div></section>`:upgradeJob?`<section class="card span-12"><div class="card-pad"><div class="lifecycle-flow"><div class="retired"><b>${fs.count}</b><span>Fleet powered down</span></div><i>→</i><div class="active"><b>${upgradeDays}</b><span>Days to ${upgradeDestination?.name||upgradeJob.id}</span></div><i>→</i><div><b>${upgradeDestination?.name||upgradeJob.id}</b><span>Site commissioning</span></div></div><p class="modal-note">${upgradeJob.down?"The move to a smaller site is underway. Mining stays offline until the fleet is re-racked and powered back on, and the old site\'s rent runs until then - the saving starts with the first full month at the new one.":"Facility upgrade is underway. Mining stays offline until the fleet is re-racked and powered back on; rent, staff and other fixed overhead still accrue."}</p></div></section>`:""}
    <section class="span-12 facility-grid facility-options">${(()=>{const nextSites=nextReleases(FACILITIES);return FACILITIES.filter(f=>f.id===state.facility||state.time>=at(f.date)||nextSites.includes(f))})().sort((a,b)=>(b.id===state.facility)-(a.id===state.facility)||at(a.date)-at(b.date)).map(f=>{const available=state.time>=at(f.date),active=f.id===state.facility;
      /* A smaller site is a different transaction from a larger one - a lease break and a
         re-rack rather than a fit-out and a reserve - and the only thing that can forbid it is
         whether the fleet fits. Both the label and the disabled state read the same helper the
         action does, so the card can never offer a move that is then refused. */
      const down=!active&&facilityIsDownsize(f.id),downBlock=down?facilityDownsizeBlockReason(f.id):"";
      const cost=down?facilityDownsizeCost(f):f.cost,reserve=down?0:facilityReserve(f);
      const blocked=active||!available||!!busy||(down?!!downBlock:state.cash<(f.cost+reserve));
      const label=active?"Operating here":!available?`Unlocks ${dateFmt(at(f.date),true)}`:upgradeJob?"Site move in progress":move?"Relocation in progress":down?`Downsize · ${fmtUsd(cost)}`:`Fit out · ${fmtUsd(cost)}`;
      const saving=down?Math.max(0,facility().rent-f.rent):0,shed=down?facilityCoolingShed(f.id):null;
      return `<article class="facility ${active?"active":""} ${available?"":"locked teaser"} ${down?"downsize":""}"><div class="risk ${active?"low":down?"low":"medium"}">${active?"Current site":!available?`<span class="next-up">Next site</span> · ${dateFmt(at(f.date),true)} · ${unlockInText(f.date)}`:down?"Smaller site":"Available"}</div><h3>${f.name}</h3><p>${f.desc}</p><div class="facility-stats"><span>${fmtNum(f.kw)} kW</span><span>${fmtNum(f.space)} space</span><span>${fmtUsd(f.rent)}/month</span></div>${down&&saving>0?`<div class="trade-sub">Rent falls ${fmtUsd(saving)}/month · lease break and re-rack ${fmtUsd(cost)}${shed&&shed.items.length?` · ${shed.items.reduce((n,i)=>n+i.qty,0)} cooling unit${shed.items.reduce((n,i)=>n+i.qty,0)===1?"":"s"} sold with the site for ${fmtUsd(shed.credit)}`:""}</div>`:""}<button class="action small ${active?"":down?"":"primary"}" data-action="facility" data-id="${f.id}"${blocked&&downBlock?` title="${escapeHtml(downBlock)}"`:""} ${blocked?"disabled":""}>${label}${!active&&available&&!busy&&!down?` · reserve ${fmtUsd(reserve)}`:""}</button></article>`}).join("")}</section>
    <section class="card span-12"><div class="card-head"><h2>Jurisdiction, grid & internet</h2><div class="meta">relocation includes 5% of fleet value</div></div><div class="card-pad facility-grid">${(()=>{const nextRegions=nextReleases(REGIONS);return REGIONS.filter(r=>r.id===state.region||state.time>=at(r.date)||nextRegions.includes(r))})().map(r=>{const closed=r.id==="sichuan"&&state.time>=at("2021-06-21"),available=state.time>=at(r.date)&&!closed,active=r.id===state.region,cost=(r.move+fs.value*.05)*(hasSkill("relocation")?.8:1)*(hasStaff("logistics")?.8:1);return `<article class="facility ${active?"active":""} ${state.time<at(r.date)?"locked teaser":""}"><div class="risk ${closed?"high":r.rely>.98?"low":r.rely>.93?"medium":"high"}">${closed?"Mining prohibited":state.time<at(r.date)?`<span class="next-up">Next location</span> · ${dateFmt(at(r.date),true)} · ${unlockInText(r.date)}`:r.policy}</div><h3>${r.name}</h3><p>${r.desc}</p><div class="facility-stats"><span>${fmtUsd(r.kwh)}/kWh</span><span>${(r.rely*100).toFixed(1)}% grid uptime</span><span>${fmtUsd(r.internet||75)}/month internet base</span></div><button class="action small" data-action="region" data-id="${r.id}" ${active||!available||state.cash<cost||!!busy?"disabled":""}>${active?"Current region":move?"Relocation in progress":upgradeJob?"Facility upgrade in progress":closed?"Closed after crackdown":available?"Relocate · "+fmtUsd(cost):"Unlocks "+dateFmt(at(r.date),true)}</button></article>`}).join("")}</div></section></div>`
}
function energy(){
  const fs=fleet(),rate=powerRate(region()),daily=dailyEnergyCostForWatts(fs.w*contractLoadFactor());return `<div class="grid"><section class="card span-12"><div class="hero"><div><div class="hero-kicker">Electricity contracts</div><h1>Know what today's mining load costs.</h1><p>Every running machine adds to the electricity bill. Fixed contracts trade a steadier rate for a higher base price; market-linked contracts may be cheaper but expose the operation to price shocks.</p></div><div class="hero-stat"><strong>${fmtUsd(rate)}/kWh</strong><span>${fmtUsd(daily)}/day at current fleet load</span></div></div><div class="metric-row"><div class="metric"><div class="label">Regional base rate</div><strong>${fmtUsd(region().kwh)}/kWh</strong><small>${region().name}</small></div><div class="metric"><div class="label">Selected contract</div><strong>${powerContract().name}</strong><small>${powerContract().mult.toFixed(2)}× price multiplier</small></div><div class="metric"><div class="label">Fleet power draw</div><strong>${fs.kw.toFixed(2)} kW</strong><small>Active mining hardware</small></div><div class="metric"><div class="label">Bill so far</div><strong>${fmtUsd(state.bill)}</strong><small>Paid at month end</small></div></div></section></div>`
}
function finance(){
  const loan=state.projectLoan||0,arrears=state.debt||0,rate=projectLoanRate(),daily=loan*rate/30.4375;return `<div class="grid"><section class="card span-12"><div class="hero"><div><div class="hero-kicker">Cash, bills and borrowing</div><h1>Finance growth without missing the next payment.</h1><p>Loans put spendable cash into the operation now, but add interest to every monthly settlement. Borrow only when the extra capacity has a credible path to cover that recurring cost.</p></div><div class="hero-stat"><strong>${fmtUsd(loan+arrears)}</strong><span>loans and unpaid bills</span></div></div><div class="metric-row"><div class="metric"><div class="label">Project loan</div><strong>${fmtUsd(loan)}</strong><small>${(rate*100).toFixed(1)}% interest each month</small></div><div class="metric"><div class="label">Interest / day</div><strong>${fmtUsd(daily)}</strong><small>Added to the month-end bill</small></div><div class="metric"><div class="label">Unpaid bills</div><strong>${fmtUsd(arrears)}</strong><small>${arrears?"Fleet currently disconnected":"Nothing overdue"}</small></div><div class="metric"><div class="label">Spendable cash</div><strong>${fmtUsd(state.cash)}</strong><small>Available for repayment</small></div></div></section></div>`
}
function learn(){
  const active=learningItem(),progress=active?Math.min(100,Math.round((state.learning.progress||0)/active.days*100)):0;
  return `<div class="grid"><section class="card span-12"><div class="hero"><div><div class="hero-kicker">Operator learning</div><h1>Knowledge compounds, one commitment at a time.</h1><p>Only one item progresses at a time. The first skill point arrives at 5 knowledge, then every 3 after - each one can reshape the underlying operation.</p></div><div class="hero-stat"><strong>${state.knowledge.toFixed(1)}</strong><span>knowledge · next skill at ${state.nextKnowledge}</span></div></div>${active?`<div class="metric-row"><div class="metric"><div class="label">Active learning</div><strong>${active.title}</strong><small>${active.type} · ${active.author}</small></div><div class="metric"><div class="label">Progress</div><strong id="learning-progress-days">${state.learning.progress||0} / ${active.days} days</strong><small id="learning-progress-percent">${progress}% complete</small></div><div class="metric"><div class="label">Reward</div><strong>${active.reward} knowledge</strong><small>${active.check?"Includes a knowledge check":"Completes automatically"}</small></div><div class="metric"><div class="label">Learning slot</div><strong>Occupied</strong><small>Finish this before choosing another</small></div></div>`:"<div class=\"metric-row\"><div class=\"metric\"><div class=\"label\">Learning slot</div><strong>Available</strong><small>Choose a book or podcast</small></div><div class=\"metric\"><div class=\"label\">Knowledge cadence</div><strong>5, then +3</strong><small>Per skill point, for the Tech tree</small></div></div>"}</section>${active&&state.learning.waiting?`<section class="card span-12"><div class="card-head"><h2>Knowledge check</h2><div class="meta">FULL REWARD IF CORRECT · 60% OTHERWISE</div></div><div class="card-pad"><p style="color:var(--muted);line-height:1.6">${active.check.q}</p><div class="actions">${active.check.options.map((answer,i)=>`<button class="action ${i===0?"primary":""}" data-action="learning-check" data-value="${i}">${answer}</button>`).join("")}</div></div></section>`:""}<section class="span-12 venue-grid">${LEARNING.filter(item=>state.completedLearning.includes(item.id)||state.learning?.id===item.id||announced(item)).map(item=>{const available=state.time>=at(item.date),done=state.completedLearning.includes(item.id),busy=!!active;return `<article class="venue ${done?"active":""} ${available?"":"locked"}"><div class="risk ${item.type==="Book"?"low":"medium"}">${item.type} · ${item.days} simulation days · ${item.reward} knowledge</div><h3>${item.title}</h3><p>${item.desc}</p><div class="trade-sub">${item.author}${item.check?" · knowledge check at completion":""}</div><button class="action small ${done?"":"primary"}" data-action="start-learning" data-id="${item.id}" ${!available||done||busy?"disabled":""}>${done?"Completed":!available?`Unlocks ${dateFmt(at(item.date),true)}`:busy?"Learning slot occupied":item.type==="Podcast"?"Subscribe & listen":"Start reading"}</button></article>`}).join("")}</section></div>`
}
