"use strict";

function eventModal(){
  const e=EVENTS.find(x=>x.id===state.activeEvent);if(!e)return"";
  const eventTime=at(e.date),laterTime=Math.min(END,eventTime+DAY*30),marketQuoted=eventTime>=MARKET,p0=priceAt(eventTime),p1=priceAt(laterTime),move=marketQuoted?(p1/p0-1)*100:null;
  return `<div class="modal-backdrop"><section class="modal event-feedback-modal${e.celebrate?" event-celebrate":""}" role="dialog" aria-modal="true" aria-labelledby="event-title"><div class="modal-top"></div><div class="modal-body">${e.celebrate?`<div class="celebrate-banner">A milestone in the story</div>`:""}<div class="modal-kicker">Historical chapter · ${dateFmt(eventTime)} · ${e.cat}</div><h2 id="event-title">${e.title}</h2><div class="event-reading"><section><span>What happened</span><p class="lead">${e.dek}</p></section><section><span>Why it mattered</span><p>${e.body}</p></section><section class="event-effect"><span>Effect on your operation</span><p>${eventGameplayEffect(e)}</p></section></div>${conferenceSceneHtml(e)}${eventReactionsHtml(e)}<div class="card-head event-market-head"><h3>What the market did next</h3><div class="meta">CONTEXT · NOT CAUSATION</div></div><div class="intro-grid"><div class="intro-fact"><b>${marketQuoted?fmtUsd(p0):"No USD market"}</b><span>BTC price on ${dateFmt(eventTime,true)}</span></div><div class="intro-fact"><b>${marketQuoted?fmtUsd(p1):"Not applicable"}</b><span>BTC price 30 days later</span></div><div class="intro-fact"><b style="color:${move===null?"var(--muted)":move>=0?"var(--green)":"var(--red)"}">${move===null?"-":`${move>=0?"+":""}${move.toFixed(1)}%`}</b><span>30-day market path</span></div></div><p class="modal-note">The price path is independent context. It does not claim this headline caused the move.</p><div class="modal-actions"><button class="action primary" data-action="close-event">${e.conference?"Return to your operation":"Continue with this effect applied"}</button></div></div></section></div>`
}
/* A LOSS IS NOT A NOTIFICATION.

   This modal exists because a toast was the wrong size for the message. It reports four things
   in a fixed order - what left, where it left from, why it was possible, and what prevents it
   next time - and the fourth is the one worth reading. The player cannot undo the loss; they
   can only change the setup that allowed it, and that is a decision they can only make if the
   game tells them what the setup was. */
function lossModal(){
  const loss=typeof pendingLoss==="function"?pendingLoss():null;if(!loss)return"";
  const queued=lossQueue().length-1;
  const kind=LOSS_KINDS[loss.kind]||LOSS_KINDS.stolen;
  return `<div class="modal-backdrop"><section class="modal loss-modal${loss.scene?` scene-${escapeHtml(loss.scene)}`:""}" role="dialog" aria-modal="true" aria-labelledby="loss-title"><div class="modal-top"></div><div class="modal-body">${typeof lossEmblemHtml==="function"?lossEmblemHtml(loss.scene):""}<div class="modal-kicker">Custody incident · time paused · ${dateFmt(loss.time)}</div><h2 id="loss-title">${escapeHtml(loss.title)}</h2><p class="lead">${fmtBtc(loss.btc)} left ${escapeHtml(loss.from)}${loss.quoted?` - ${fmtUsd(loss.usd)} at today's price`:""}. ${escapeHtml(kind.note)}</p><div class="intro-grid"><div class="intro-fact"><b class="down">${fmtBtc(loss.btc)}</b><span>${kind.label.toLowerCase()}</span></div>${loss.recovered>0?`<div class="intro-fact"><b>${fmtBtc(loss.recovered)}</b><span>frozen · a claim, not a balance</span></div>`:""}<div class="intro-fact"><b>${loss.quoted?fmtUsd(loss.usd):"No USD market"}</b><span>value when it left</span></div><div class="intro-fact"><b>${fmtBtc(totalBtc()+lightningLocked())}</b><span>total BTC remaining</span></div></div><div class="event-reading"><section><span>What happened</span><p class="lead">${escapeHtml(loss.what)}</p></section><section><span>Why it was possible</span><p>${escapeHtml(loss.why)}</p></section><section class="event-effect"><span>Reducing this risk</span><p>${escapeHtml(loss.remedy)}</p></section></div>${loss.oddsText?`<p class="modal-odds">${escapeHtml(loss.oddsText)}</p>`:""}<p class="modal-note">Recorded in the activity ledger under custody. ${queued>0?`${queued} further incident${queued===1?"":"s"} to review after this one.`:"The clock resumes when you close this."}</p><div class="modal-actions"><button class="action" data-action="tab" data-value="${escapeHtml(loss.tab)}">Open ${escapeHtml(loss.tab)}</button><button class="action primary" data-action="close-loss">Acknowledge this loss</button></div></div></section></div>`
}
